using HouseManagement.Domain.Entities;

public static class ShoppingSuggestionSeed
{
  public static IEnumerable<ShoppingSuggestion> Get()
  {
    return new List<ShoppingSuggestion>
    {
      // Pães e Padaria
      Create("Pão Francês", "pao frances"),
      Create("Pão de Forma", "pao de forma"),
      Create("Pão Integral", "pao integral"),
      Create("Pão de Queijo", "pao de queijo"),
      Create("Pão de Mel", "pao de mel"),
      Create("Pão Sírio", "pao sirio"),
      Create("Pão Hot Dog", "pao hot dog"),
      Create("Pão Hambúrguer", "pao hamburguer"),
      Create("Bisnaguinha", "bisnaguinha"),
      Create("Baguete", "baguete"),

      // Grãos e Cereais
      Create("Arroz Branco", "arroz branco"),
      Create("Arroz Integral", "arroz integral"),
      Create("Arroz Parboilizado", "arroz parboilizado"),
      Create("Feijão Carioca", "feijao carioca"),
      Create("Feijão Preto", "feijao preto"),
      Create("Feijão Branco", "feijao branco"),
      Create("Lentilha", "lentilha"),
      Create("Grão de Bico", "grao de bico"),
      Create("Ervilha Seca", "ervilha seca"),
      Create("Milho Verde", "milho verde"),
      Create("Milho para Pipoca", "milho para pipoca"),
      Create("Aveia em Flocos", "aveia em flocos"),
      Create("Quinoa", "quinoa"),
      Create("Trigo para Quibe", "trigo para quibe"),
      Create("Canjica", "canjica"),

      // Farinhas e Massas
      Create("Farinha de Trigo", "farinha de trigo"),
      Create("Farinha de Mandioca", "farinha de mandioca"),
      Create("Farinha de Milho", "farinha de milho"),
      Create("Amido de Milho", "amido de milho"),
      Create("Polvilho Azedo", "polvilho azedo"),
      Create("Polvilho Doce", "polvilho doce"),
      Create("Macarrão Espaguete", "macarrao espaguete"),
      Create("Macarrão Parafuso", "macarrao parafuso"),
      Create("Macarrão Penne", "macarrao penne"),
      Create("Macarrão Instantâneo", "macarrao instantaneo"),
      Create("Lasanha", "lasanha"),
      Create("Macarrão Talharim", "macarrao talharim"),

      // Carnes Bovinas
      Create("Carne Moída", "carne moida"),
      Create("Fraldinha", "fraldinha"),
      Create("Alcatra", "alcatra"),
      Create("Picanha", "picanha"),
      Create("Costela Bovina", "costela bovina"),
      Create("Patinho", "patinho"),
      Create("Acém", "acem"),
      Create("Maminha", "maminha"),
      Create("Contra-filé", "contra-file"),
      Create("Filé Mignon", "file mignon"),
      Create("Músculo", "musculo"),
      Create("Coxão Mole", "coxao mole"),
      Create("Coxão Duro", "coxao duro"),

      // Frango e Aves
      Create("Frango Inteiro", "frango inteiro"),
      Create("Peito de Frango", "peito de frango"),
      Create("Coxa de Frango", "coxa de frango"),
      Create("Sobrecoxa de Frango", "sobrecoxa de frango"),
      Create("Asa de Frango", "asa de frango"),
      Create("Filé de Frango", "file de frango"),
      Create("Frango Moído", "frango moido"),
      Create("Linguiça de Frango", "linguica de frango"),
      Create("Peru", "peru"),
      Create("Pato", "pato"),

      // Suínos
      Create("Lombo Suíno", "lombo suino"),
      Create("Costela Suína", "costela suina"),
      Create("Linguiça Calabresa", "linguica calabresa"),
      Create("Linguiça Toscana", "linguica toscana"),
      Create("Bacon", "bacon"),
      Create("Presunto", "presunto"),
      Create("Salame", "salame"),
      Create("Mortadela", "mortadela"),
      Create("Apresuntado", "apresuntado"),
      Create("Pernil Suíno", "pernil suino"),

      // Peixes e Frutos do Mar
      Create("Filé de Tilápia", "file de tilapia"),
      Create("Filé de Merluza", "file de merluza"),
      Create("Salmão", "salmao"),
      Create("Atum em Lata", "atum em lata"),
      Create("Sardinha em Lata", "sardinha em lata"),
      Create("Camarão", "camarao"),
      Create("Bacalhau", "bacalhau"),
      Create("Peixe Inteiro", "peixe inteiro"),
      Create("Lula", "lula"),
      Create("Polvo", "polvo"),

      // Laticínios
      Create("Leite Integral", "leite integral"),
      Create("Leite Desnatado", "leite desnatado"),
      Create("Leite Semidesnatado", "leite semidesnatado"),
      Create("Leite Condensado", "leite condensado"),
      Create("Creme de Leite", "creme de leite"),
      Create("Iogurte Natural", "iogurte natural"),
      Create("Iogurte Grego", "iogurte grego"),
      Create("Manteiga", "manteiga"),
      Create("Margarina", "margarina"),
      Create("Nata", "nata"),
      Create("Requeijão", "requeijao"),
      Create("Creme de Queijo", "creme de queijo"),

      // Queijos
      Create("Queijo Mussarela", "queijo mussarela"),
      Create("Queijo Prato", "queijo prato"),
      Create("Queijo Minas", "queijo minas"),
      Create("Queijo Parmesão", "queijo parmesao"),
      Create("Queijo Coalho", "queijo coalho"),
      Create("Queijo Ricota", "queijo ricota"),
      Create("Queijo Gorgonzola", "queijo gorgonzola"),
      Create("Queijo Brie", "queijo brie"),
      Create("Queijo Camembert", "queijo camembert"),
      Create("Queijo Provolone", "queijo provolone"),

      // Ovos
      Create("Ovos de Galinha", "ovos de galinha"),
      Create("Ovos Caipira", "ovos caipira"),
      Create("Ovos de Codorna", "ovos de codorna"),

      // Óleos e Gorduras
      Create("Óleo de Soja", "oleo de soja"),
      Create("Óleo de Girassol", "oleo de girassol"),
      Create("Óleo de Canola", "oleo de canola"),
      Create("Azeite de Oliva", "azeite de oliva"),
      Create("Óleo de Coco", "oleo de coco"),
      Create("Banha de Porco", "banha de porco"),

      // Açúcares e Adoçantes
      Create("Açúcar Cristal", "acucar cristal"),
      Create("Açúcar Refinado", "acucar refinado"),
      Create("Açúcar Mascavo", "acucar mascavo"),
      Create("Açúcar Demerara", "acucar demerara"),
      Create("Mel", "mel"),
      Create("Adoçante", "adocante"),
      Create("Stevia", "stevia"),
      Create("Melado de Cana", "melado de cana"),

      // Temperos e Condimentos
      Create("Sal Refinado", "sal refinado"),
      Create("Sal Grosso", "sal grosso"),
      Create("Sal Rosa do Himalaia", "sal rosa do himalaia"),
      Create("Pimenta do Reino", "pimenta do reino"),
      Create("Pimenta Vermelha", "pimenta vermelha"),
      Create("Páprica", "paprica"),
      Create("Cúrcuma", "curcuma"),
      Create("Cominho", "cominho"),
      Create("Canela em Pó", "canela em po"),
      Create("Canela em Rama", "canela em rama"),
      Create("Cravo", "cravo"),
      Create("Noz-Moscada", "noz-moscada"),
      Create("Orégano", "oregano"),
      Create("Manjericão", "manjericao"),
      Create("Alecrim", "alecrim"),
      Create("Tomilho", "tomilho"),
      Create("Louro", "louro"),
      Create("Curry", "curry"),
      Create("Colorau", "colorau"),
      Create("Tempero Completo", "tempero completo"),
      Create("Caldo de Frango", "caldo de frango"),
      Create("Caldo de Carne", "caldo de carne"),
      Create("Caldo de Legumes", "caldo de legumes"),
      Create("Vinagre de Álcool", "vinagre de alcool"),
      Create("Vinagre de Maçã", "vinagre de maca"),
      Create("Vinagre Balsâmico", "vinagre balsamico"),
      Create("Molho Shoyu", "molho shoyu"),
      Create("Molho de Pimenta", "molho de pimenta"),
      Create("Molho Inglês", "molho ingles"),
      Create("Ketchup", "ketchup"),
      Create("Mostarda", "mostarda"),
      Create("Maionese", "maionese"),
      Create("Molho de Tomate", "molho de tomate"),
      Create("Extrato de Tomate", "extrato de tomate"),
      Create("Polpa de Tomate", "polpa de tomate"),

      // Hortifruti - Verduras
      Create("Alface", "alface"),
      Create("Rúcula", "rucula"),
      Create("Espinafre", "espinafre"),
      Create("Couve", "couve"),
      Create("Repolho", "repolho"),
      Create("Acelga", "acelga"),
      Create("Agrião", "agriao"),
      Create("Brócolis", "brocolis"),
      Create("Couve-Flor", "couve-flor"),
      Create("Aipo", "aipo"),
      Create("Salsinha", "salsinha"),
      Create("Cebolinha", "cebolinha"),
      Create("Coentro", "coentro"),
      Create("Hortelã", "hortela"),

      // Hortifruti - Legumes
      Create("Tomate", "tomate"),
      Create("Cebola", "cebola"),
      Create("Alho", "alho"),
      Create("Batata", "batata"),
      Create("Batata Doce", "batata doce"),
      Create("Cenoura", "cenoura"),
      Create("Beterraba", "beterraba"),
      Create("Abobrinha", "abobrinha"),
      Create("Berinjela", "berinjela"),
      Create("Pimentão Verde", "pimentao verde"),
      Create("Pimentão Vermelho", "pimentao vermelho"),
      Create("Pimentão Amarelo", "pimentao amarelo"),
      Create("Chuchu", "chuchu"),
      Create("Pepino", "pepino"),
      Create("Milho Verde em Espiga", "milho verde em espiga"),
      Create("Mandioca", "mandioca"),
      Create("Inhame", "inhame"),
      Create("Abóbora", "abobora"),
      Create("Jiló", "jilo"),
      Create("Quiabo", "quiabo"),
      Create("Vagem", "vagem"),
      Create("Ervilha Fresca", "ervilha fresca"),
      Create("Cogumelo", "cogumelo"),
      Create("Alho-Poró", "alho-poro"),
      Create("Rabanete", "rabanete"),
      Create("Nabo", "nabo"),

      // Frutas
      Create("Banana Nanica", "banana nanica"),
      Create("Banana Prata", "banana prata"),
      Create("Maçã", "maca"),
      Create("Pera", "pera"),
      Create("Laranja", "laranja"),
      Create("Limão", "limao"),
      Create("Limão Siciliano", "limao siciliano"),
      Create("Uva", "uva"),
      Create("Morango", "morango"),
      Create("Melancia", "melancia"),
      Create("Melão", "melao"),
      Create("Manga", "manga"),
      Create("Abacaxi", "abacaxi"),
      Create("Mamão Formosa", "mamao formosa"),
      Create("Mamão Papaya", "mamao papaya"),
      Create("Abacate", "abacate"),
      Create("Coco", "coco"),
      Create("Goiaba", "goiaba"),
      Create("Maracujá", "maracuja"),
      Create("Pêssego", "pessego"),
      Create("Ameixa", "ameixa"),
      Create("Nectarina", "nectarina"),
      Create("Cereja", "cereja"),
      Create("Kiwi", "kiwi"),
      Create("Caqui", "caqui"),
      Create("Figo", "figo"),
      Create("Framboesa", "framboesa"),
      Create("Mirtilo", "mirtilo"),
      Create("Acerola", "acerola"),
      Create("Carambola", "carambola"),

      // Bebidas
      Create("Água Mineral", "agua mineral"),
      Create("Água com Gás", "agua com gas"),
      Create("Suco de Laranja", "suco de laranja"),
      Create("Suco de Uva", "suco de uva"),
      Create("Suco de Maracujá", "suco de maracuja"),
      Create("Néctar de Pêssego", "nectar de pessego"),
      Create("Refrigerante Cola", "refrigerante cola"),
      Create("Refrigerante Guaraná", "refrigerante guarana"),
      Create("Refrigerante Limão", "refrigerante limao"),
      Create("Refrigerante Laranja", "refrigerante laranja"),
      Create("Cerveja", "cerveja"),
      Create("Vinho Tinto", "vinho tinto"),
      Create("Vinho Branco", "vinho branco"),
      Create("Vinho Rosé", "vinho rose"),
      Create("Espumante", "espumante"),
      Create("Café em Pó", "cafe em po"),
      Create("Café Solúvel", "cafe soluvel"),
      Create("Café em Cápsula", "cafe em capsula"),
      Create("Chá Preto", "cha preto"),
      Create("Chá Verde", "cha verde"),
      Create("Chá de Camomila", "cha de camomila"),
      Create("Chá de Erva-Doce", "cha de erva-doce"),
      Create("Achocolatado", "achocolatado"),
      Create("Energético", "energetico"),
      Create("Isotônico", "isotonico"),
      Create("Água de Coco", "agua de coco"),

      // Congelados e Processados
      Create("Pizza Congelada", "pizza congelada"),
      Create("Lasanha Congelada", "lasanha congelada"),
      Create("Hambúrguer Congelado", "hamburguer congelado"),
      Create("Nuggets de Frango", "nuggets de frango"),
      Create("Batata Frita Congelada", "batata frita congelada"),
      Create("Peixe Empanado", "peixe empanado"),
      Create("Camarão Congelado", "camarao congelado"),
      Create("Ervilha Congelada", "ervilha congelada"),
      Create("Milho Congelado", "milho congelado"),
      Create("Espinafre Congelado", "espinafre congelado"),
      Create("Sorvete de Creme", "sorvete de creme"),
      Create("Sorvete de Chocolate", "sorvete de chocolate"),
      Create("Picolé", "picole"),
      Create("Massa de Pastel", "massa de pastel"),

      // Enlatados e Conservas
      Create("Milho em Lata", "milho em lata"),
      Create("Ervilha em Lata", "ervilha em lata"),
      Create("Palmito", "palmito"),
      Create("Azeitona", "azeitona"),
      Create("Alcachofra", "alcachofra"),
      Create("Cogumelo em Lata", "cogumelo em lata"),
      Create("Tomate Pelado", "tomate pelado"),
      Create("Creme de Milho", "creme de milho"),
      Create("Feijão em Lata", "feijao em lata"),
      Create("Lentilha em Lata", "lentilha em lata"),

      // Biscoitos e Snacks
      Create("Biscoito Cream Cracker", "biscoito cream cracker"),
      Create("Biscoito de Maisena", "biscoito de maisena"),
      Create("Biscoito Recheado", "biscoito recheado"),
      Create("Biscoito de Polvilho", "biscoito de polvilho"),
      Create("Biscoito Wafer", "biscoito wafer"),
      Create("Bolacha Maria", "bolacha maria"),
      Create("Chips de Batata", "chips de batata"),
      Create("Salgadinho de Milho", "salgadinho de milho"),
      Create("Pipoca Microondas", "pipoca microondas"),
      Create("Torrada", "torrada"),
      Create("Granola", "granola"),
      Create("Barra de Cereal", "barra de cereal"),
      Create("Amendoim", "amendoim"),
      Create("Castanha do Pará", "castanha do para"),
      Create("Castanha de Caju", "castanha de caju"),
      Create("Nozes", "nozes"),
      Create("Amêndoa", "amendoa"),
      Create("Pistache", "pistache"),

      // Doces e Sobremesas
      Create("Chocolate Ao Leite", "chocolate ao leite"),
      Create("Chocolate Amargo", "chocolate amargo"),
      Create("Chocolate Branco", "chocolate branco"),
      Create("Chocolate em Pó", "chocolate em po"),
      Create("Achocolatado em Pó", "achocolatado em po"),
      Create("Creme de Avelã", "creme de avela"),
      Create("Gelatina", "gelatina"),
      Create("Pudim", "pudim"),
      Create("Doce de Leite", "doce de leite"),
      Create("Goiabada", "goiabada"),
      Create("Geleia de Morango", "geleia de morango"),
      Create("Geleia de Uva", "geleia de uva"),
      Create("Bala", "bala"),
      Create("Chiclete", "chiclete"),
      Create("Marshmallow", "marshmallow"),

      // Itens de Padaria / Confeitaria
      Create("Fermento Biológico", "fermento biologico"),
      Create("Fermento Químico", "fermento quimico"),
      Create("Bicarbonato de Sódio", "bicarbonato de sodio"),
      Create("Extrato de Baunilha", "extrato de baunilha"),
      Create("Coco Ralado", "coco ralado"),
      Create("Uva Passa", "uva passa"),
      Create("Ameixa Seca", "ameixa seca"),
      Create("Damasco Seco", "damasco seco"),
      Create("Cobertura de Chocolate", "cobertura de chocolate"),
      Create("Granulado de Chocolate", "granulado de chocolate"),
      Create("Waffle", "waffle"),

      // Limpeza Doméstica
      Create("Detergente Líquido", "detergente liquido"),
      Create("Sabão em Pó", "sabao em po"),
      Create("Sabão em Barra", "sabao em barra"),
      Create("Amaciante de Roupas", "amaciante de roupas"),
      Create("Alvejante", "alvejante"),
      Create("Desinfetante", "desinfetante"),
      Create("Água Sanitária", "agua sanitaria"),
      Create("Limpador Multiuso", "limpador multiuso"),
      Create("Limpa Vidro", "limpa vidro"),
      Create("Limpa Banheiro", "limpa banheiro"),
      Create("Tira Manchas", "tira manchas"),
      Create("Esponja de Limpeza", "esponja de limpeza"),
      Create("Palha de Aço", "palha de aco"),
      Create("Pano de Prato", "pano de prato"),
      Create("Rodo", "rodo"),
      Create("Vassoura", "vassoura"),
      Create("Mop", "mop"),
      Create("Saco de Lixo", "saco de lixo"),
      Create("Inseticida", "inseticida"),
      Create("Repelente", "repelente"),
      Create("Aromatizador de Ambiente", "aromatizador de ambiente"),

      // Higiene Pessoal
      Create("Shampoo", "shampoo"),
      Create("Condicionador", "condicionador"),
      Create("Sabonete", "sabonete"),
      Create("Sabonete Líquido", "sabonete liquido"),
      Create("Creme Hidratante", "creme hidratante"),
      Create("Protetor Solar", "protetor solar"),
      Create("Desodorante", "desodorante"),
      Create("Creme Dental", "creme dental"),
      Create("Escova de Dente", "escova de dente"),
      Create("Fio Dental", "fio dental"),
      Create("Enxaguante Bucal", "enxaguante bucal"),
      Create("Papel Higiênico", "papel higienico"),
      Create("Lenço de Papel", "lenco de papel"),
      Create("Absorvente", "absorvente"),
      Create("Algodão", "algodao"),
      Create("Cotonete", "cotonete"),
      Create("Lâmina de Barbear", "lamina de barbear"),
      Create("Creme de Barbear", "creme de barbear"),
      Create("Talco", "talco"),
      Create("Perfume", "perfume"),
      Create("Álcool Gel", "alcool gel"),
      Create("Álcool 70%", "alcool 70"),

      // Bebê
      Create("Fralda Descartável", "fralda descartavel"),
      Create("Lenço Umedecido", "lenco umedecido"),
      Create("Pomada para Assadura", "pomada para assadura"),
      Create("Shampoo Infantil", "shampoo infantil"),
      Create("Sabonete Infantil", "sabonete infantil"),
      Create("Talco Infantil", "talco infantil"),
      Create("Leite em Pó Infantil", "leite em po infantil"),
      Create("Papinha Infantil", "papinha infantil"),

      // Pet
      Create("Ração para Cachorro", "racao para cachorro"),
      Create("Ração para Gato", "racao para gato"),
      Create("Petisco para Cachorro", "petisco para cachorro"),
      Create("Areia para Gato", "areia para gato"),
      Create("Shampoo para Pets", "shampoo para pets"),

      // Descartáveis e Utensílios
      Create("Papel Alumínio", "papel aluminio"),
      Create("Papel Toalha", "papel toalha"),
      Create("Filme Plástico", "filme plastico"),
      Create("Prato Descartável", "prato descartavel"),
      Create("Copo Descartável", "copo descartavel"),
      Create("Garfo e Faca Descartável", "garfo e faca descartavel"),
      Create("Palito de Dente", "palito de dente"),
      Create("Guardanapo de Papel", "guardanapo de papel"),
      Create("Vela", "vela"),
      Create("Fósforo", "fosforo"),
      Create("Isqueiro", "isqueiro"),
      Create("Pilha AA", "pilha aa"),
      Create("Pilha AAA", "pilha aaa"),
      Create("Lâmpada LED", "lampada led"),

      // Medicamentos e Farmácia
      Create("Paracetamol", "paracetamol"),
      Create("Dipirona", "dipirona"),
      Create("Ibuprofeno", "ibuprofeno"),
      Create("Antiácido", "antiacido"),
      Create("Vitamina C", "vitamina c"),
      Create("Vitamina D", "vitamina d"),
      Create("Complexo B", "complexo b"),
      Create("Band-Aid", "band-aid"),
      Create("Gaze", "gaze"),
      Create("Esparadrapo", "esparadrapo"),
      Create("Termômetro", "termometro"),
      Create("Pomada Antibiótica", "pomada antibiotica"),

      // Orgânicos e Naturais
      Create("Leite Vegetal de Amêndoa", "leite vegetal de amendoa"),
      Create("Leite de Aveia", "leite de aveia"),
      Create("Leite de Coco", "leite de coco"),
      Create("Tofu", "tofu"),
      Create("Proteína de Soja", "proteina de soja"),
      Create("Farinha de Amendoim", "farinha de amendoim"),
      Create("Pasta de Amendoim", "pasta de amendoim"),
      Create("Tahine", "tahine"),
      Create("Chia", "chia"),
      Create("Linhaça", "linhaca"),
      Create("Gergelim", "gergelim"),
      Create("Spirulina", "spirulina"),
      Create("Whey Protein", "whey protein"),
      Create("Proteína Vegana", "proteina vegana"),
      Create("Creatina", "creatina"),

      // Molhos e Temperos Prontos
      Create("Molho Pesto", "molho pesto"),
      Create("Molho Barbecue", "molho barbecue"),
      Create("Molho Tarê", "molho tare"),
      Create("Molho Tahine", "molho tahine"),
      Create("Tempero para Churrasco", "tempero para churrasco"),
      Create("Tempero para Frango", "tempero para frango"),
      Create("Tempero para Peixe", "tempero para peixe"),
      Create("Tempero para Feijão", "tempero para feijao"),
      Create("Caldo de Camarão", "caldo de camarao"),

      // Produtos para Churrasco
      Create("Carvão", "carvao"),
      Create("Acendedor de Carvão", "acendedor de carvao"),
      Create("Espeto de Churrasco", "espeto de churrasco"),

      // Massas Frescas e Especiais
      Create("Nhoque", "nhoque"),
      Create("Ravioli", "ravioli"),
      Create("Capeletti", "capeletti"),
      Create("Tortellini", "tortellini"),

      // Sopas e Caldos Prontos
      Create("Sopa de Legumes", "sopa de legumes"),
      Create("Caldo de Carne Pronto", "caldo de carne pronto"),
      Create("Sopa de Frango", "sopa de frango"),
      Create("Sopa de Tomate", "sopa de tomate"),

      // Frutas Secas e Exóticas
      Create("Tâmara", "tamara"),
      Create("Cranberry Seco", "cranberry seco"),
      Create("Goji Berry", "goji berry"),
      Create("Baru", "baru"),
      Create("Macadâmia", "macadamia"),

      // Produtos Étnicos / Regionais
      Create("Tapioca", "tapioca"),
      Create("Cuscuz", "cuscuz"),
      Create("Paçoca", "pacoca"),
      Create("Rapadura", "rapadura"),
      Create("Tucupi", "tucupi"),
      Create("Açaí", "acai"),
      Create("Cupuaçu", "cupuacu"),
      Create("Guaraná em Pó", "guarana em po"),
      Create("Pimenta Biquinho", "pimenta biquinho"),
      Create("Pimenta Dedo de Moça", "pimenta dedo de moca"),

      // Pratos Prontos
      Create("Feijoada Pronta", "feijoada pronta"),
      Create("Frango Assado Pronto", "frango assado pronto"),
      Create("Marmita Congelada", "marmita congelada"),
      Create("Arroz de Forno Pronto", "arroz de forno pronto"),
      Create("Coxinha", "coxinha"),
      Create("Pastel", "pastel"),
      Create("Esfiha", "esfiha"),
      Create("Kibe", "kibe"),

      // Itens de Escritório / Escola
      Create("Caderno", "caderno"),
      Create("Caneta", "caneta"),
      Create("Lápis", "lapis"),
      Create("Borracha", "borracha"),
      Create("Cola", "cola"),
      Create("Tesoura", "tesoura"),
      Create("Fita Adesiva", "fita adesiva"),
      Create("Post-it", "post-it"),

      // Itens Sazonais / Festivos
      Create("Panetone", "panetone"),
      Create("Chocotone", "chocotone"),
      Create("Ovo de Páscoa", "ovo de pascoa"),
      Create("Cesta de Café da Manhã", "cesta de cafe da manha"),

      // Suplementos e Saúde
      Create("Colágeno", "colageno"),
      Create("Ômega 3", "omega 3"),
      Create("Probiótico", "probiotico"),
      Create("Magnésio", "magnesio"),
      Create("Ferro", "ferro"),
      Create("Cálcio", "calcio"),
      Create("Zinco", "zinco"),
      Create("Melatonina", "melatonina"),

      // Culinária Internacional
      Create("Molho de Ostra", "molho de ostra"),
      Create("Misso", "misso"),
      Create("Nori", "nori"),
      Create("Arroz para Sushi", "arroz para sushi"),
      Create("Wasabi", "wasabi"),
      Create("Gengibre em Conserva", "gengibre em conserva"),
      Create("Páprica Defumada", "paprica defumada"),
      Create("Za'atar", "zaatar"),
      Create("Sumac", "sumac"),
      Create("Anis Estrelado", "anis estrelado"),
      Create("Cardamomo", "cardamomo"),
      Create("Açafrão", "acafrao"),

      // Diversos / Outros
      Create("Fermento de Cerveja", "fermento de cerveja"),
      Create("Gelatina sem Sabor", "gelatina sem sabor"),
      Create("Agar Agar", "agar agar"),
      Create("Lecitina de Soja", "lecitina de soja"),
      Create("Pectina", "pectina"),
      Create("Creme de Tártaro", "creme de tartaro"),
      Create("Água de Flor de Laranjeira", "agua de flor de laranjeira"),
      Create("Água de Rosas", "agua de rosas"),
      Create("Extrato de Amêndoa", "extrato de amendoa"),
      Create("Corante Alimentar", "corante alimentar"),
    };
  }

  private static ShoppingSuggestion Create(string name, string nameNormalized) =>
    new()
    {
      Id = Guid.NewGuid(),
      Name = name,
      NameNormalized = nameNormalized,
      UsageCount = 0,
      LastUsedAt = new DateTime(2025, 1, 1, 0, 0, 0, DateTimeKind.Utc)
    };
}